[package]
name = "kos-proto"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[features]

[dependencies]
bytes = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
pbjson = { workspace = true }
pbjson-types = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[lib]
test = false
doctest = false

[build-dependencies]
prost-build = "0.11"
prost-wkt-build = "0.4"
quote = "1.0.9"
heck = " 0.3.3"
pbjson-build = { version = "0.5", git = "https://github.com/klever-io/pbjson" }
