[package]
name = "kos-proto"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[features]

[dependencies]
kos-types = { workspace = true }

bytes = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
prost-wkt = "0.4"
prost-wkt-types = "0.4"
pbjson = { workspace = true }
pbjson-types = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[lib]
test = false
doctest = false

[build-dependencies]
glob = "0.3"
prost-build = "0.11"
prost-wkt-build = "0.4"
quote = "1.0"
heck = " 0.4"
pbjson-build = { workspace = true }
