[package]
name = "kos-mobile"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"

[dependencies]
kos-crypto = { workspace = true }
kos-types = { workspace = true, features = ["serde"] }
kos = { workspace = true }

hex = { workspace = true }
lazy_static = { workspace = true }
thiserror = { workspace = true }

uniffi = { workspace = true, features = ["cli"] }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }