[package]
name = "kos-mobile"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[features]
default = ["serde"]

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"

[dependencies]
kos = { workspace = true, default-features = false }
kos-codec = { path = "../kos-codec", default-features = false }

hex = { workspace = true }
thiserror = { workspace = true }

uniffi = { workspace = true, features = ["cli"] }
serde = { workspace = true, features = ["derive"], optional = true }
num-bigint = { version = "0.4", default-features = false }
num-traits = { version = "0.2", default-features = false }
lwk_common = { workspace = true }
lwk_signer = { workspace = true }
lwk_wollet = { workspace = true }
anyhow = { version = "1.0.96", default-features = false }
ecies = { workspace = true }
bigdecimal = { version = "0.4.7", default-features = false }


[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
