[package]
name = "kos-ios"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kos-crypto = { workspace = true }
kos-types = { workspace = true }

[lib]
name = "kos_ios"
crate-type = ["staticlib", "cdylib"]
