[target.x86_64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-undefined",
    "-C",
    "link-arg=dynamic_lookup",
    "-C",
    "link-arg=-Wl,-install_name,@rpath/libkos_mobile.dylib",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-undefined",
    "-C",
    "link-arg=dynamic_lookup",
    "-C",
    "link-arg=-Wl,-install_name,@rpath/libkos_mobile.dylib",
]

[target.aarch64-apple-ios]
rustflags = [
    "-C",
    "link-arg=-undefined",
    "-C",
    "link-arg=dynamic_lookup",
    "-C",
    "link-arg=-Wl,-install_name,@rpath/libkos_mobile.dylib",
]

[target.x86_64-apple-ios]
rustflags = [
    "-C",
    "link-arg=-undefined",
    "-C",
    "link-arg=dynamic_lookup",
    "-C",
    "link-arg=-Wl,-install_name,@rpath/libkos_mobile.dylib",
]

[target.aarch64-apple-ios-sim]
rustflags = [
    "-C",
    "link-arg=-undefined",
    "-C",
    "link-arg=dynamic_lookup",
    "-C",
    "link-arg=-Wl,-install_name,@rpath/libkos_mobile.dylib",
]

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
rustflags = ["-C", "target-feature=+crt-static"]
