[package]
name = "kos-web"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["serde"]

[dependencies]
strum = { version = "0.26.3", features = ["derive"] }
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true }
serde-wasm-bindgen = "0.5"
qrcode-generator = "4.1"
enum_delegate = { workspace = true }
hex = { workspace = true }
enum_dispatch = "0.3"
pem = "3"
postcard = { version = "1.0.6", features = ["use-std"] }
lazy_static = { workspace = true }
kos = { workspace = true, features = ["not-ksafe"] }
wasm-bindgen = { workspace = true }
num-bigint = "0.4"
num-traits = "0.2"
kos-codec = { path = "../kos-codec" }

