[package]
name = "kos-types"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
rand = { workspace = true }
coins-bip32 = { workspace = true }
coins-bip39 = { workspace = true }
secp256k1 = { workspace = true, features = ["recovery", "rand"] }
ed25519-dalek = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
hex = { workspace = true }
wasm-bindgen = { workspace = true }
