name: KOS-Go Checks

on:
  push:
    paths:
      - 'packages/kos-go/kos_mobile/**'
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-go-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
 
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: RustUp
        uses: klever-io/kos-rs/.github/actions/rustup@develop
        with:
          with_cache: true

      - name: Run Go tests
        run: |
          cd packages/kos-go
          make test

  build-go-linux-musl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
 
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: RustUp
        uses: klever-io/kos-rs/.github/actions/rustup@develop
        with:
          with_cache: true
  
      - name: Install musl tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Run Go tests
        run: |
          cd packages/kos-go
          make test-linux-musl

  build-go-mac:
    runs-on: [ "macos-14" ]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Rust toolchain
        shell: bash
        run: |
          set -e
          rustup component add --toolchain stable rustfmt clippy
          rustup default stable

      - name: Setup protobuf
        run: brew install protobuf

      - name: Run Go tests
        run: |
          cd packages/kos-go
          make test
