name: KOS-RS NPM Dev Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      USER: ${{ secrets.GIT_USER }}
      TOKEN: ${{ secrets.GIT_PASS }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
        
      - name: RustUp
        uses: klever-io/kos-rs/.github/actions/rustup@develop
        with:
          with_cache: true

      - name: Restore .env file
        run: echo $NODES_ENV | base64 -d > packages/kos-sdk/.env.nodes
        env:
          NODES_ENV: ${{ secrets.NODES_ENV }}

      - name: Build
        run: make webpack-npm

      - name: Set NPM package release version
        run: bash .github/actions/npm-package-version.sh

      - name: Setup npm module
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@klever'
          always-auth: true

      - name: Publish npm module
        run: npm publish ./demo/kos --access public --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
