name: KOS-RS Checks

on:
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.github/**'
  pull_request:
    branches:
      - develop
      - master
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.github/**'
    
jobs:
  format:
    runs-on: ubuntu-latest
    env:
      USER: ${{ secrets.GIT_USER }}
      TOKEN: ${{ secrets.GIT_PASS }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: RustUp
        uses: klever-io/kos-rs/.github/actions/rustup@develop
        with:
          with_cache: true

      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings

      - name: checks
        run: |
          cargo deny check
          cargo pants

      - name: Restore .env file
        run: |
          echo "${{ vars.NODES_ENV }}" > packages/kos-sdk/.env.nodes

      - name: Run Tests
        run: cargo test

  build:
    needs: [format]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: RustUp
        uses: klever-io/kos-rs/.github/actions/rustup@develop
        with:
          with_cache: true

      - name: Restore .env file
        run: echo $NODES_ENV | base64 -d > packages/kos-sdk/.env.nodes
        env:
          NODES_ENV: ${{ secrets.NODES_ENV }}

      - name: Build
        run: make webpack-npm
