name: Release KOS-RS

on:
  pull_request:
    branches:
      - develop
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Set up Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
      - name: Build
        run: make webpack-npm