# .github/workflows/welcome.yml
name: Welcome

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        issue-message: 'Thanks for reporting your first issue! Make sure to follow the issue template, so we can help you more easily.'
        pr-message: 'Thanks for creating your first PR! Please check the contribution guidelines, and ensure your PR adheres to them.'
